services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbwp
      MYSQL_USER: userwp
      MYSQL_PASSWORD: passwp
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    ports:
      - "8090:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: userwp
      WORDPRESS_DB_PASSWORD: passwp
      WORDPRESS_DB_NAME: dbwp
    depends_on:
      - mysql
    networks:
      - wp_network

volumes:
  db_data:

networks:
  wp_network:
